# Audio Visualizer Configuration Example
# This file shows the available configuration options.
# The actual config will be saved automatically when you use the application.

hostname = "127.0.0.1"    # Server hostname or IP address
port = 8080               # Server port number
num_bands = 64            # Number of frequency bands (8-256)
gain = 1.0                # Audio gain/amplification (0.1-5.0)
smoothing = 0.8           # Smoothing factor (0.0-0.99)
min_freq = 20.0           # Minimum frequency in Hz
max_freq = 20000.0        # Maximum frequency in Hz

# Common configurations:
#
# For LED strips (32 LEDs):
# num_bands = 32
# gain = 1.5
# smoothing = 0.7
#
# For high-resolution displays:
# num_bands = 128
# gain = 1.0
# smoothing = 0.9
#
# For bass-heavy music:
# min_freq = 20.0
# max_freq = 8000.0
# gain = 2.0
